### ISSUE TITLE
Créer une entrée pour le RAM sur le launcher

### ISSUE THREAD

**Issue by Bricklou** [TheShark34/OpenLauncherLib#6]
Bonjour,
Après avoir lu et relu votre code source, je n'ai pas compris où il fallait mettre le code pour choisir le RAM. Pouvez-vous m'aider ?

Cordialement,
Bricklou

PS: Pour S-Update suite à ma dernière question, le problème venait des droit d'utilisateur. Tous les fichier devaient appartenir à l'utilisateur de apache(www-data), ce qui n'était pas la cas. Je pense que beaucoup d'utilisateur de Linux risque d'avoir le même problème en voulant l'utiliser.

**Comment by TheShark34** [comment]
Dans les arguments VM ;)

SU : Ce n'est pas un problème, c'est normal, il faut bien qu'il écrive les fichiers.

**Comment by Bricklou** [comment]
J'ai mis à jour OpenLauncherLibs en version 3.0 et plein d'erreur sont apparues.
Il y a une erreur que je n'ai pas pu corriger:
private static final **LauncherClasspath** LC_B_CP = **new LauncherClasspath**(new File(LC_DIR, "Launcher/launcher.jar"), new File(LC_DIR, "Launcher/Libs/"));

Existerait-il une classe pouvant remplacer LauncherClasspath.

**Comment by TheShark34** [comment]
https://www.youtube.com/watch?v=54jKg_oNsQA

**Comment by TheShark34** [comment]
https://www.youtube.com/watch?v=54jKg_oNsQA
